# Generated by Django 4.2.5 on 2023-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_created_alter_filmwork_modified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genrefilmwork',
            name='film_work_genre_idx',
        ),
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='film_work_person_idx',
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'genre_id'), name='film_work_genre_idx'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'person_id', 'role'), name='film_work_person_idx'),
        ),
    ]
