version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always


  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django_web
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./data:/data/:ro
    depends_on:
      - postgres


  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./data:/data/:ro
    depends_on:
      - web
    ports:
      - "80:80"
      - "8000:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:

